### ISSUE TITLE
Is it possible to run on Debian?

### ISSUE THREAD

**Issue by giovi321** [j6k4m8/remailable#30]
Could you share a few high level instructions on how to run this on Debian, please?

**Comment by j6k4m8** [comment]
Hi @giovi321! There will probably be a lot of configuration and engineering required if you want to run your own service on on-prem hardware:

* mail server — using SES from AWS was a major advantage here in particular because of DKIM et al
* file storage with callbacks — we use AWS S3 to trigger the function to upload the document; there are some s3-API emulators out there that might be able to handle this?
* lambdas and compute — this part is easy if you can kick off a python script from your file-storage / s3-replacement

In short, I'm not sure this is the right tool to run if you don't want to engage some cloud resources. That said, for personal use, deploying this on AWS will almost certainly be free, as all of the usage is extremely light and well within free-tier limits on all applicable services.

If you want to run a standalone service locally, you could forego this repository entirely and investigate receiving mail through something like postfix and using a cron job to move pdf/epub attachments to the device with `rmapi` directly! Food for thought!

**Comment by giovi321** [comment]
Oh that's a very good idea, so simple that I haven't thought of it! Thank you so much :)

**Comment by j6k4m8** [comment]
My pleasure! I'm going to close this issue if it's okay with you, but of course happy to discuss other strategies to do this :)
